// 店铺管理原型数据
window.PRINCIPAL_DATA = [
  { id: 81, name: '深圳市鸿娇长益科技有限公司', code: '91440300MA5HP6A08B', type: '大陆企业', enterpriseRegistrationTime: '2023-03-09' },
  { id: 67, name: '香港諾威科創有限公司', code: 'BR-72631891', type: '香港企业', enterpriseRegistrationTime: '2022-11-18' },
  { id: 66, name: '香港星辉贸易有限公司', code: 'BR-55091230', type: '香港企业', enterpriseRegistrationTime: '2021-06-30' },
  { id: 80, name: 'Pratchaya Phaipa', code: '—', type: '个人', enterpriseRegistrationTime: '—' },
  { id: 71, name: 'PT HORIZON TECHNOLOGY INDONESIA', code: '—', type: '海外企业', enterpriseRegistrationTime: '2024-02-14' },
  { id: 90, name: '云易盒科技有限公司', code: '91440300MA5YYH0001', type: '大陆企业', enterpriseRegistrationTime: '2020-12-08' },
  { id: 91, name: '云易盒科技美国', code: 'US-EIN-88319022', type: '海外企业', enterpriseRegistrationTime: '2021-09-16' }
];

window.STORE_DATA = [
  {
    id: 1,
    platform: 'Shopee',
    name: 'Shopee MY 旗舰店',
    alias: '东南亚主力店',
    body: '云易盒科技有限公司',
    subName: '—',
    site: 'MY',
    region: '',
    storeType: '本土店',
    platformStoreType: '优选店铺',
    bu: '东南亚事业部',
    status: '启用',
    authStatus: '已授权',
    authTime: '2026-05-19 10:30',
    authExpire: '2027-05-19 10:30',
    authType: 'shop_account',
    mainAccountId: null,
    isSip: false,
    isMall: true,
    syncOrderTime: '2026-05-19 14:00',
    operator: '张三',
    cs: '王五',
    platformShopId: '12345',
    platformShopName: 'Main Store MY',
    merchantId: null,
    useStatus: '正常使用',
    enabled: true,
    cancelDate: null,
    dept: '东南亚事业部',
    owner: '张三',
    browserName: '紫鸟',
    browserStoreName: 'MY旗舰店浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    registrationDate: '2025-12-08',
    fundPlatform: 'PingPong',
    fundAccount: '**** **** 3821',
    fundAccountRaw: 'pingpong-my-3821@yiyihe.com',
    fundAccountId: 'PP-MY-3821',
    aeFreightAlipay: '',
    hasDeposit: true,
    depositRefundStatus: '未退回',
    depositAccount: '**** 9018',
    depositAccountRaw: 'deposit-my-9018',
    depositAmount: '12,000.00',
    depositRefundTime: '',
    depositRefundTransactionId: '',
    remarks: '主力经营店铺，订单同步频率较高。',
    adAuthStatus: '已授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    storeEmail: 'shopee-my@yiyihe.com',
    paymentAccounts: [
      { platform: 'PingPong', account: '**** **** 3821', accountRaw: 'pingpong-my-3821@yiyihe.com', accountId: 'PP-MY-3821', currency: 'USD' },
      { platform: 'WorldFirst', account: '**** **** 6390', accountRaw: 'wf-my-6390@yiyihe.com', accountId: 'WF-MY-6390', currency: 'MYR' },
      { platform: '连连支付', account: '**** **** 2107', accountRaw: 'lianlian-my-2107@yiyihe.com', accountId: 'LL-MY-2107', currency: 'USD' }
    ],
    bodyChangeRecords: [
      { time: '2026-05-18 15:42', operator: 'Freddy', from: '云易盒贸易有限公司', to: '云易盒科技有限公司' },
      { time: '2026-04-02 10:16', operator: '张三', from: '云易盒跨境事业部', to: '云易盒贸易有限公司' }
    ],
    paymentChangeRecords: [
      { time: '2026-05-19 11:20', operator: 'Freddy', content: '新增 WorldFirst 收款账号 WF-MY-6390，用于 MYR 回款' },
      { time: '2026-05-18 16:05', operator: 'Freddy', content: '店铺主体变更后，主收款账号由 PingPong PP-OLD-9201 调整为 PP-MY-3821' },
      { time: '2026-04-10 09:36', operator: '张三', content: '新增连连支付备用收款账号 LL-MY-2107' }
    ],
    permissions: ['订单查看', '商品管理', '库存同步', '资金信息查看'],
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 2,
    platform: 'Shopee',
    name: 'Shopee SG 专营店',
    alias: '新加坡店',
    body: '云易盒科技有限公司',
    subName: '—',
    site: 'SG',
    region: '',
    storeType: '跨境店（CNSC）',
    platformStoreType: '商城店铺',
    bu: '东南亚事业部',
    status: '启用',
    authStatus: '已授权',
    authTime: '2026-05-19 10:30',
    authExpire: '2027-05-19 10:30',
    authType: 'main_account',
    mainAccountId: 'main_acct_10001',
    isSip: false,
    isMall: false,
    syncOrderTime: '2026-05-19 14:00',
    operator: '张三',
    cs: '王五',
    platformShopId: '23456',
    platformShopName: 'CNSC Shop SG',
    merchantId: 'merchant_1001705',
    useStatus: '正常使用',
    enabled: true,
    cancelDate: null,
    dept: '东南亚事业部',
    owner: '张三',
    browserName: '紫鸟',
    browserStoreName: 'SG专营店浏览器',
    accountType: '购买',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    registrationDate: '2025-10-21',
    fundPlatform: 'WorldFirst',
    fundAccount: '**** **** 6679',
    fundAccountRaw: 'wf-sg-6679@yiyihe.com',
    fundAccountId: 'WF-SG-6679',
    aeFreightAlipay: '',
    hasDeposit: true,
    depositRefundStatus: '已退回',
    depositAccount: '**** 3302',
    depositAccountRaw: 'deposit-sg-3302',
    depositAmount: '8,000.00',
    depositRefundTime: '2026-04-18',
    depositRefundTransactionId: 'ALP202604180091',
    remarks: '通过主账号授权录入。',
    adAuthStatus: '已授权',
    affiliateAuthStatus: '已授权',
    relatedStores: ['Shopee MY 旗舰店', 'Shopee TH 跨境店'],
    unrecordedStores: 2,
    storeEmail: 'shopee-sg@yiyihe.com',
    paymentAccounts: [
      { platform: 'WorldFirst', account: '**** **** 6679', accountRaw: 'wf-sg-6679@yiyihe.com', accountId: 'WF-SG-6679', currency: 'SGD' },
      { platform: 'PingPong', account: '**** **** 8752', accountRaw: 'pingpong-sg-8752@yiyihe.com', accountId: 'PP-SG-8752', currency: 'USD' }
    ],
    bodyChangeRecords: [
      { time: '2026-05-17 14:10', operator: '李四', from: '云易盒科技香港有限公司', to: '云易盒科技有限公司' }
    ],
    paymentChangeRecords: [
      { time: '2026-05-17 14:18', operator: '李四', content: '主体变更后同步更新 WorldFirst 收款账号归属证明' },
      { time: '2026-05-12 18:02', operator: 'Freddy', content: '新增 PingPong 备用账号 PP-SG-8752' }
    ],
    permissions: ['订单查看', '商品管理', '资金信息查看'],
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 3,
    platform: 'Shopee',
    name: 'Shopee TH 跨境店',
    alias: '泰国3PF',
    body: '云易盒科技有限公司',
    subName: '—',
    site: 'TH',
    region: '',
    storeType: '3PF',
    platformStoreType: '普通店铺',
    bu: '东南亚事业部',
    status: '启用',
    authStatus: '即将过期',
    authTime: '2025-06-01 09:00',
    authExpire: '2026-05-25 09:00',
    authType: 'main_account',
    mainAccountId: 'main_acct_10002',
    isSip: true,
    isMall: false,
    syncOrderTime: '2026-05-19 13:30',
    operator: '李四',
    cs: '赵六',
    platformShopId: '34567',
    platformShopName: '3PF Shop TH',
    merchantId: 'merchant_1001706',
    useStatus: '正常使用',
    enabled: true,
    cancelDate: null,
    dept: '东南亚事业部',
    owner: '李四',
    browserName: '战斧',
    browserStoreName: 'TH跨境店浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    registrationDate: '2025-09-02',
    fundPlatform: 'PingPong',
    fundAccount: '**** **** 7712',
    fundAccountRaw: 'pingpong-th-7712@yiyihe.com',
    fundAccountId: 'PP-TH-7712',
    aeFreightAlipay: '',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    depositAccount: '',
    depositAccountRaw: '',
    depositAmount: '',
    depositRefundTime: '',
    depositRefundTransactionId: '',
    remarks: 'SIP 店铺，库存推送需要关注授权到期。',
    adAuthStatus: '已授权',
    affiliateAuthStatus: '未授权',
    relatedStores: ['Shopee SG 专营店'],
    unrecordedStores: 0,
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 4,
    platform: 'Amazon',
    name: 'Amazon US Store',
    alias: '美国站',
    body: '云易盒科技美国',
    subName: '—',
    site: 'US',
    region: '北美',
    storeType: '',
    platformStoreType: '专业卖家',
    bu: '北美事业部',
    status: '启用',
    authStatus: '已授权',
    authTime: '2026-03-01 10:00',
    authExpire: '2027-03-01 10:00',
    authType: null,
    mainAccountId: null,
    isSip: false,
    syncOrderTime: '2026-05-19 12:00',
    operator: '陈七',
    cs: '周八',
    platformShopId: 'A1B2C3',
    platformShopName: 'US Store',
    merchantId: null,
    useStatus: '正常使用',
    enabled: true,
    cancelDate: null,
    dept: '北美事业部',
    owner: '陈七',
    browserName: '紫鸟',
    browserStoreName: 'Amazon US 浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技美国',
    registrationDate: '2024-12-12',
    fundPlatform: 'Payoneer',
    fundAccount: '**** **** 1209',
    fundAccountRaw: 'payoneer-us-1209@yiyihe.com',
    fundAccountId: 'PY-US-1209',
    aeFreightAlipay: '',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    depositAccount: '',
    depositAccountRaw: '',
    depositAmount: '',
    depositRefundTime: '',
    depositRefundTransactionId: '',
    remarks: 'Amazon SP-API 授权店铺。',
    adAuthStatus: '已授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    ops: ['详情', '编辑', '更多']
  },
  {
    id: 22,
    platform: 'AliExpress',
    name: 'AliExpress 半托管店',
    alias: 'AE半托管主店',
    body: '云易盒科技有限公司',
    subName: '—',
    site: '',
    region: '',
    storeType: '半托管',
    platformStoreType: '—',
    bu: '东南亚事业部',
    status: '启用',
    authStatus: '已授权',
    authTime: '2026-04-15 09:30',
    authExpire: '2027-04-15 09:30',
    authType: 'oauth',
    mainAccountId: null,
    isSip: false,
    syncOrderTime: '2026-05-19 11:20',
    operator: '张三',
    cs: '王五',
    platformShopId: 'AE-880086',
    platformShopName: 'YIYIHE AliExpress',
    merchantId: null,
    useStatus: '正常使用',
    enabled: true,
    cancelDate: null,
    dept: '东南亚事业部',
    owner: '张三',
    storeEmail: 'aliexpress@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: 'AE半托管浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    remarks: 'AliExpress 店铺类型为全托管/半托管。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    paymentAccounts: [],
    bodyChangeRecords: [],
    paymentChangeRecords: [],
    permissions: ['订单查看', '商品管理'],
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 5,
    platform: 'Shopee',
    name: '—',
    alias: '待授权新店',
    body: '云易盒科技有限公司',
    subName: '—',
    site: 'VN',
    region: '',
    storeType: '本土店',
    platformStoreType: '—',
    bu: '东南亚事业部',
    status: '停用',
    authStatus: '未授权',
    authTime: '—',
    authExpire: '—',
    authType: null,
    mainAccountId: null,
    isSip: false,
    isMall: false,
    syncOrderTime: '—',
    operator: '—',
    cs: '—',
    platformShopId: null,
    platformShopName: null,
    merchantId: null,
    useStatus: '待授权',
    enabled: false,
    cancelDate: null,
    dept: '东南亚事业部',
    owner: '—',
    browserName: '',
    browserStoreName: '',
    accountType: '',
    registrationType: '',
    registrationCompany: '',
    registrationDate: '',
    fundPlatform: '',
    fundAccount: '',
    fundAccountRaw: '',
    fundAccountId: '',
    aeFreightAlipay: '',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    depositAccount: '',
    depositAccountRaw: '',
    depositAmount: '',
    depositRefundTime: '',
    depositRefundTransactionId: '',
    remarks: '待完成 Shopee 授权。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 6,
    platform: 'TikTok Shop',
    name: 'TikTok ID 官方店',
    alias: '印尼内容店',
    body: '云易盒科技有限公司',
    subName: '—',
    site: 'ID',
    region: '',
    storeType: '',
    platformStoreType: 'Mall',
    bu: '东南亚事业部',
    status: '启用',
    authStatus: '已授权',
    authTime: '2026-05-10 11:00',
    authExpire: '2027-05-10 11:00',
    authType: 'oauth',
    mainAccountId: null,
    isSip: false,
    syncOrderTime: '2026-05-19 13:00',
    operator: '李四',
    cs: '赵六',
    platformShopId: 'TTS-77881',
    platformShopName: 'TikTok ID Official',
    merchantId: null,
    useStatus: '正常使用',
    enabled: true,
    cancelDate: null,
    dept: '东南亚事业部',
    owner: '李四',
    storeEmail: 'tiktok-id@yiyihe.com',
    adAccountId: '7642613372432859144',
    adAccountName: 'TIKShop-美区主户',
    bcId: 'bc_448201',
    isMall: true,
    adAccounts: [
      {
        id: '7642613372432859144',
        name: 'TIKShop-美区主户',
        status: 'STATUS_ENABLE',
        statusLabel: '启用中',
        balance: 250,
        is_del: 0,
        ad_create_time: '2026-03-12 09:20',
        lastAuthTime: '2026-08-05 10:00'
      },
      {
        id: '7123456789012345678',
        name: 'TIKShop-美区备用户',
        status: 'STATUS_ENABLE',
        statusLabel: '启用中',
        balance: 0,
        is_del: 0,
        ad_create_time: '2026-08-01 10:00',
        lastAuthTime: '2026-08-05 10:00'
      }
    ],
    browserName: '紫鸟',
    browserStoreName: 'TikTok ID 浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    registrationDate: '2026-01-18',
    fundPlatform: 'PingPong',
    fundAccount: '**** **** 9021',
    fundAccountRaw: 'pingpong-tt-9021@yiyihe.com',
    fundAccountId: 'PP-TT-9021',
    aeFreightAlipay: '',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    depositAccount: '',
    depositAccountRaw: '',
    depositAmount: '',
    depositRefundTime: '',
    depositRefundTransactionId: '',
    remarks: 'TikTok 广告授权后需设置广告数据更新时段。',
    adAuthStatus: '已授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    paymentAccounts: [
      { platform: 'PingPong', account: '**** **** 9021', accountRaw: 'pingpong-tt-9021@yiyihe.com', accountId: 'PP-TT-9021', currency: 'USD' },
      { platform: 'WorldFirst', account: '**** **** 1188', accountRaw: 'wf-tt-1188@yiyihe.com', accountId: 'WF-TT-1188', currency: 'IDR' }
    ],
    bodyChangeRecords: [
      { time: '2026-05-12 09:20', operator: 'Freddy', from: '云易盒贸易有限公司', to: '云易盒科技有限公司' }
    ],
    paymentChangeRecords: [
      { time: '2026-05-18 16:30', operator: 'Freddy', content: '新增 WorldFirst 收款账号 WF-TT-1188' }
    ],
    permissions: ['订单查看', '商品管理', '库存同步'],
    adSyncSetting: null,
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 7,
    platform: 'Temu',
    name: 'Temu012',
    alias: 'Temu012_US',
    temuBaseAlias: 'Temu012',
    temuGroupId: 'TG-Temu012',
    temuRegionKey: 'us',
    relationRole: 'temu-site',
    body: '云易盒科技有限公司',
    subName: '—',
    site: '',
    region: '美区',
    storeType: '全托管',
    platformStoreType: '—',
    bu: '北美事业部',
    status: '启用',
    authStatus: '已授权',
    authTime: '2026-08-05 07:39',
    authExpire: '2027-08-05 07:39',
    authType: 'token',
    mainAccountId: null,
    isSip: false,
    syncOrderTime: '2026-08-05 07:39',
    operator: '张三',
    cs: '王五',
    platformShopId: 'TEMU-US-10086',
    platformShopName: 'YIYIHE Temu US',
    merchantId: null,
    useStatus: '正常使用',
    enabled: true,
    cancelDate: null,
    dept: '北美事业部',
    owner: '张三',
    storeEmail: 'temu-us@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: 'Temu US 浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    registrationDate: '2025-11-01',
    fundPlatform: 'PingPong',
    fundAccount: '**** **** 5566',
    fundAccountRaw: 'pingpong-temu-5566@yiyihe.com',
    fundAccountId: 'PP-TEMU-5566',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    depositAccount: '',
    depositAccountRaw: '',
    depositAmount: '',
    depositRefundTime: '',
    depositRefundTransactionId: '',
    remarks: 'Temu 店铺按区域拆分为独立店铺；仅别名与区域不同。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    orderPullTokens: {
      us: { accessToken: 'us_order_access_token_demo', appKey: 'us_app_key_demo', appSecret: 'us_app_secret_demo' },
      eu: { accessToken: '', appKey: '', appSecret: '' },
      global: { accessToken: '', appKey: '', appSecret: '' }
    },
    productPullToken: {
      accessToken: 'product_access_token_demo',
      appKey: 'product_app_key_demo',
      appSecret: 'product_app_secret_demo'
    },
    temuAuthEdited: true,
    paymentAccounts: [
      { platform: 'PingPong', account: '**** **** 5566', accountRaw: 'pingpong-temu-5566@yiyihe.com', accountId: 'PP-TEMU-5566', currency: 'USD' }
    ],
    bodyChangeRecords: [],
    paymentChangeRecords: [],
    permissions: ['订单查看', '商品管理'],
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 23,
    platform: 'Temu',
    name: 'Temu012',
    alias: 'Temu012_EU',
    temuBaseAlias: 'Temu012',
    temuGroupId: 'TG-Temu012',
    temuRegionKey: 'eu',
    relationRole: 'temu-site',
    body: '云易盒科技有限公司',
    subName: '—',
    site: '',
    region: '欧区',
    storeType: '全托管',
    platformStoreType: '—',
    bu: '北美事业部',
    status: '启用',
    authStatus: '已授权',
    authTime: '2026-05-20 10:00',
    authExpire: '2027-05-20 10:00',
    authType: 'token',
    mainAccountId: null,
    isSip: false,
    syncOrderTime: '2026-05-20 10:05',
    operator: '张三',
    cs: '王五',
    platformShopId: 'TEMU-US-10086',
    platformShopName: 'YIYIHE Temu US',
    merchantId: null,
    useStatus: '正常使用',
    enabled: true,
    cancelDate: null,
    dept: '北美事业部',
    owner: '张三',
    storeEmail: 'temu-us@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: 'Temu US 浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    registrationDate: '2025-11-01',
    fundPlatform: 'PingPong',
    fundAccount: '**** **** 5566',
    fundAccountRaw: 'pingpong-temu-5566@yiyihe.com',
    fundAccountId: 'PP-TEMU-5566',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    depositAccount: '',
    depositAccountRaw: '',
    depositAmount: '',
    depositRefundTime: '',
    depositRefundTransactionId: '',
    remarks: 'Temu 店铺按区域拆分为独立店铺；仅别名与区域不同。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    orderPullTokens: {
      us: { accessToken: '', appKey: '', appSecret: '' },
      eu: { accessToken: 'eu_order_access_token_demo', appKey: 'eu_app_key_demo', appSecret: 'eu_app_secret_demo' },
      global: { accessToken: '', appKey: '', appSecret: '' }
    },
    productPullToken: {
      accessToken: 'product_access_token_demo',
      appKey: 'product_app_key_demo',
      appSecret: 'product_app_secret_demo'
    },
    temuAuthEdited: true,
    paymentAccounts: [
      { platform: 'PingPong', account: '**** **** 5566', accountRaw: 'pingpong-temu-5566@yiyihe.com', accountId: 'PP-TEMU-5566', currency: 'USD' }
    ],
    bodyChangeRecords: [],
    paymentChangeRecords: [],
    permissions: ['订单查看', '商品管理'],
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 8,
    platform: '1688',
    name: '1688 企业采购店',
    alias: '1688主店',
    body: '云易盒科技有限公司',
    subName: '—',
    site: '',
    region: '中国',
    storeType: '',
    platformStoreType: '—',
    bu: '东南亚事业部',
    status: '启用',
    authStatus: '已授权',
    authTime: '2026-04-01 09:00',
    authExpire: '2027-04-01 09:00',
    authType: 'token',
    mainAccountId: null,
    isSip: false,
    syncOrderTime: '2026-05-19 08:00',
    operator: '张三',
    cs: '王五',
    platformShopId: '1688-220011',
    platformShopName: '云易盒1688官方',
    useStatus: '正常使用',
    enabled: true,
    dept: '供应链事业部',
    owner: '张三',
    storeEmail: '1688@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: '1688 浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    remarks: '1688 店铺通过跳转授权完成授权。',
    accessToken: '6200819d9366af1383023a19907ZZf9048e4c14fd56333b263685215',
    alibabaAuthEdited: true,
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    paymentAccounts: [],
    bodyChangeRecords: [],
    paymentChangeRecords: [],
    permissions: ['订单查看', '商品管理'],
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 9,
    platform: '淘宝',
    name: '淘宝云易盒旗舰店',
    alias: '淘宝旗舰',
    body: '云易盒科技有限公司',
    subName: '—',
    site: '',
    region: '中国',
    storeType: '',
    platformStoreType: '—',
    bu: '东南亚事业部',
    status: '启用',
    authStatus: '即将过期',
    authTime: '2025-08-01 10:00',
    authExpire: '2026-08-05 10:00',
    authType: null,
    mainAccountId: null,
    isSip: false,
    syncOrderTime: '2026-05-19 09:00',
    operator: '李四',
    cs: '赵六',
    platformShopId: 'TB-88001',
    platformShopName: '云易盒淘宝店',
    useStatus: '正常使用',
    enabled: true,
    dept: '国内电商部',
    owner: '李四',
    storeEmail: 'taobao@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: '淘宝浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    remarks: '淘宝店铺 OAuth 授权（交互同 Amazon）。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    paymentAccounts: [],
    bodyChangeRecords: [],
    paymentChangeRecords: [],
    permissions: ['订单查看', '商品管理'],
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 10,
    platform: '天猫',
    name: '天猫云易盒官方旗舰店',
    alias: '天猫旗舰',
    body: '云易盒科技有限公司',
    subName: '—',
    site: '',
    region: '中国',
    storeType: '',
    platformStoreType: '—',
    bu: '东南亚事业部',
    status: '启用',
    authStatus: '未授权',
    authTime: '—',
    authExpire: '—',
    authType: null,
    mainAccountId: null,
    isSip: false,
    syncOrderTime: '—',
    operator: '李四',
    cs: '赵六',
    platformShopId: 'TM-99001',
    platformShopName: '云易盒天猫旗舰店',
    useStatus: '待启用',
    enabled: false,
    dept: '国内电商部',
    owner: '李四',
    storeEmail: 'tmall@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: '天猫浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    remarks: '天猫店铺 OAuth 授权（交互同 Amazon）。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    paymentAccounts: [],
    bodyChangeRecords: [],
    paymentChangeRecords: [],
    permissions: ['订单查看'],
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 11,
    platform: 'Ozon',
    name: 'Ozon RU 官方店',
    alias: 'Ozon俄区店',
    body: '云易盒科技有限公司',
    subName: '—',
    site: '',
    region: '俄罗斯',
    storeType: '',
    platformStoreType: '—',
    bu: '拉美事业部',
    status: '启用',
    authStatus: '已授权',
    authTime: '2026-05-18 15:00',
    authExpire: '无限期',
    useStatus: '正常使用',
    enabled: true,
    dept: '跨境电商部',
    owner: '张三',
    storeEmail: 'ozon-ru@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: 'Ozon RU 浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    clientId: '248861',
    apiKey: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    ozonAuthEdited: true,
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    remarks: 'Ozon 店铺通过 Client ID / API Key 维护授权。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    paymentAccounts: [],
    bodyChangeRecords: [],
    paymentChangeRecords: [],
    operationLogs: [
      {
        time: '2026-05-18 15:00',
        operator: 'Freddy',
        module: '授权',
        type: '编辑',
        content: 'Client ID：（空） → 248861；API Key：（空） → a1b2c3d4-e5f6-7890-abcd-ef1234567890；授权状态：未授权 → 已授权；授权时间：— → 2026-05-18 15:00；过期时间：— → 2027-05-18 15:00'
      },
      {
        time: '2026-05-18 14:40',
        operator: 'Freddy',
        module: '基础资料',
        type: '新增',
        content: '创建 Ozon 店铺记录'
      }
    ],
    permissions: ['订单查看', '商品管理'],
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 12,
    platform: 'Lazada',
    name: 'Lazada MY 跨境店',
    alias: 'Lazada马跨境',
    body: '云易盒科技有限公司',
    subName: '—',
    site: 'MY',
    region: '',
    storeType: '跨境',
    platformStoreType: '—',
    bu: '东南亚事业部',
    status: '启用',
    authStatus: '已授权',
    authTime: '2026-05-10 11:00',
    authExpire: '2027-05-10 11:00',
    authType: 'oauth',
    mainAccountId: null,
    isSip: false,
    isMall: false,
    syncOrderTime: '2026-05-19 12:00',
    operator: '张三',
    cs: '王五',
    platformShopId: 'LZD-MY-88001',
    platformShopName: 'YIYIHE Lazada MY',
    merchantId: null,
    useStatus: '正常使用',
    enabled: true,
    cancelDate: null,
    dept: '东南亚事业部',
    owner: '张三',
    storeEmail: 'lazada-my@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: 'Lazada MY 浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    remarks: 'Lazada 店铺类型为跨境/本土。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    paymentAccounts: [],
    bodyChangeRecords: [],
    paymentChangeRecords: [],
    permissions: ['订单查看', '商品管理'],
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 13,
    platform: '京东',
    name: '京东云易盒旗舰店',
    alias: '京东旗舰',
    body: '云易盒科技有限公司',
    site: '',
    storeType: '',
    platformStoreType: '—',
    bu: '国内电商部',
    status: '启用',
    authStatus: '未授权',
    authTime: '—',
    authExpire: '—',
    syncOrderTime: '—',
    operator: '李四',
    cs: '赵六',
    platformShopId: 'JD-10001',
    platformShopName: '云易盒京东旗舰店',
    useStatus: '正常使用',
    enabled: true,
    dept: '国内电商部',
    owner: '李四',
    storeEmail: 'jd@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: '京东浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    remarks: '其他平台 · 京东，支持内联填写 appKey / token / refresh_token 授权。',
    appKey: '',
    token: '',
    refreshToken: '',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    paymentAccounts: [],
    permissions: ['订单查看'],
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 14,
    platform: '抖音',
    name: '抖音云易盒小店',
    alias: '抖音小店',
    body: '云易盒科技有限公司',
    site: '',
    storeType: '',
    platformStoreType: '—',
    bu: '国内电商部',
    status: '启用',
    authStatus: '未授权',
    authTime: '—',
    authExpire: '—',
    syncOrderTime: '—',
    operator: '李四',
    cs: '赵六',
    platformShopId: 'DY-20001',
    platformShopName: '云易盒抖音店',
    useStatus: '正常使用',
    enabled: true,
    dept: '国内电商部',
    owner: '李四',
    storeEmail: 'douyin@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: '抖音浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    remarks: '其他平台 · 抖音，无立即授权。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    paymentAccounts: [],
    permissions: ['订单查看'],
    ops: ['详情', '编辑', '更多']
  },
  {
    id: 15,
    platform: '美客多',
    name: 'Mercado Libre MX Store',
    alias: '美客多墨站',
    body: '云易盒科技有限公司',
    site: '',
    storeType: '',
    platformStoreType: '—',
    bu: '拉美事业部',
    status: '启用',
    authStatus: '未授权',
    authTime: '—',
    authExpire: '—',
    syncOrderTime: '—',
    operator: '张三',
    cs: '王五',
    platformShopId: 'ML-MX-30001',
    platformShopName: 'YIYIHE Mercado MX',
    useStatus: '正常使用',
    enabled: true,
    dept: '拉美事业部',
    owner: '张三',
    storeEmail: 'mercadolibre@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: '美客多浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    remarks: '其他平台 · 美客多，无立即授权。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    paymentAccounts: [],
    permissions: ['订单查看'],
    ops: ['详情', '编辑', '更多']
  },
  {
    id: 16,
    platform: '沃尔玛',
    name: 'Walmart US Store',
    alias: '沃尔玛美站',
    body: '云易盒科技美国',
    site: '',
    storeType: '',
    platformStoreType: '—',
    bu: '北美事业部',
    status: '启用',
    authStatus: '未授权',
    authTime: '—',
    authExpire: '—',
    syncOrderTime: '—',
    operator: '陈七',
    cs: '周八',
    platformShopId: 'WMT-US-40001',
    platformShopName: 'YIYIHE Walmart US',
    useStatus: '正常使用',
    enabled: true,
    dept: '北美事业部',
    owner: '陈七',
    storeEmail: 'walmart@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: '沃尔玛浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技美国',
    remarks: '其他平台 · 沃尔玛，无立即授权。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    paymentAccounts: [],
    permissions: ['订单查看'],
    ops: ['详情', '编辑', '更多']
  },
  {
    id: 17,
    platform: 'Wish',
    name: 'Wish Global Store',
    alias: 'Wish主店',
    body: '云易盒科技有限公司',
    site: '',
    storeType: '',
    platformStoreType: '—',
    bu: '北美事业部',
    status: '启用',
    authStatus: '未授权',
    authTime: '—',
    authExpire: '—',
    syncOrderTime: '—',
    operator: '陈七',
    cs: '周八',
    platformShopId: 'WISH-50001',
    platformShopName: 'YIYIHE Wish',
    useStatus: '正常使用',
    enabled: true,
    dept: '北美事业部',
    owner: '陈七',
    storeEmail: 'wish@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: 'Wish浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    remarks: '其他平台 · Wish，无立即授权。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    paymentAccounts: [],
    permissions: ['订单查看'],
    ops: ['详情', '编辑', '更多']
  },
  {
    id: 18,
    platform: '阿里巴巴国际',
    name: 'Alibaba.com 国际站',
    alias: '阿里国际站',
    body: '云易盒科技有限公司',
    site: '',
    storeType: '',
    platformStoreType: '—',
    bu: '供应链事业部',
    status: '启用',
    authStatus: '未授权',
    authTime: '—',
    authExpire: '—',
    syncOrderTime: '—',
    operator: '张三',
    cs: '王五',
    platformShopId: 'ICBU-60001',
    platformShopName: 'YIYIHE Alibaba',
    useStatus: '正常使用',
    enabled: true,
    dept: '供应链事业部',
    owner: '张三',
    storeEmail: 'alibaba@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: '阿里国际浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    remarks: '其他平台 · 阿里巴巴国际，无立即授权。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    paymentAccounts: [],
    permissions: ['订单查看'],
    ops: ['详情', '编辑', '更多']
  },
  {
    id: 19,
    platform: 'B2C',
    name: 'B2C 独立站旗舰',
    alias: 'B2C旗舰',
    body: '云易盒科技有限公司',
    site: '',
    storeType: '',
    platformStoreType: '—',
    bu: '北美事业部',
    status: '启用',
    authStatus: '未授权',
    authTime: '—',
    authExpire: '—',
    syncOrderTime: '—',
    operator: '陈七',
    cs: '周八',
    platformShopId: 'B2C-70001',
    platformShopName: 'YIYIHE B2C',
    useStatus: '正常使用',
    enabled: true,
    dept: '北美事业部',
    owner: '陈七',
    storeEmail: 'b2c@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: 'B2C浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    remarks: '其他平台 · B2C，无立即授权。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    paymentAccounts: [],
    permissions: ['订单查看'],
    ops: ['详情', '编辑', '更多']
  },
  {
    id: 20,
    platform: 'Shopify',
    name: 'Shopify US Store',
    alias: 'Shopify美站',
    body: '云易盒科技美国',
    site: '',
    storeType: '',
    platformStoreType: '—',
    bu: '北美事业部',
    status: '启用',
    authStatus: '未授权',
    authTime: '—',
    authExpire: '—',
    syncOrderTime: '—',
    operator: '陈七',
    cs: '周八',
    platformShopId: 'SHP-80001',
    platformShopName: 'yiyihe.myshopify.com',
    useStatus: '正常使用',
    enabled: true,
    dept: '北美事业部',
    owner: '陈七',
    storeEmail: 'shopify@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: 'Shopify浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技美国',
    remarks: '其他平台 · Shopify，无立即授权。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    paymentAccounts: [],
    permissions: ['订单查看'],
    ops: ['详情', '编辑', '更多']
  },
  {
    id: 21,
    platform: 'Wildberries',
    name: 'Wildberries RU Store',
    alias: 'WB俄站',
    body: '云易盒科技有限公司',
    site: '',
    storeType: '',
    platformStoreType: '—',
    bu: '拉美事业部',
    status: '启用',
    authStatus: '未授权',
    authTime: '—',
    authExpire: '—',
    syncOrderTime: '—',
    operator: '张三',
    cs: '王五',
    platformShopId: 'WB-90001',
    platformShopName: 'YIYIHE Wildberries',
    useStatus: '正常使用',
    enabled: true,
    dept: '拉美事业部',
    owner: '张三',
    storeEmail: 'wildberries@yiyihe.com',
    browserName: '紫鸟',
    browserStoreName: 'WB浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    remarks: '其他平台 · Wildberries，无立即授权。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    paymentAccounts: [],
    permissions: ['订单查看'],
    ops: ['详情', '编辑', '更多']
  }
];

// 授权状态标签映射
window.AUTH_STATUS_MAP = {
  '已授权':   { tag: 'tag-green',  text: '已授权' },
  '即将过期':  { tag: 'tag-orange', text: '即将过期' },
  '已过期':   { tag: 'tag-red',    text: '已过期' },
  '未授权':   { tag: 'tag-gray',   text: '未授权' },
  'Token失效': { tag: 'tag-red',    text: 'Token 失效' },
};
